default: &default
  adapter: postgresql
  min_messages: WARNING
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: postgres
  password: postgres

development:
  <<: *default
  database: monopoly_development

production:
  <<: *default
  database: monopoly_patients_production

test: &test
  <<: *default
  database: monopoly__patients_test

